// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bikeShopWebAPI.Models;

namespace bikeShopWebAPI.Migrations
{
    [DbContext(typeof(BikeDetailContext))]
    partial class BikeDetailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("bikeShopWebAPI.Models.BikeDetail", b =>
                {
                    b.Property<int>("BikeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BikeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("BikePrice")
                        .HasColumnType("decimal(18,0)");

                    b.Property<bool>("BikeRented")
                        .HasColumnType("bit");

                    b.Property<string>("BikeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BikeID");

                    b.ToTable("BikeDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
